### ISSUE TITLE
Not all strings are translated - Customize the quotes in ACP 

### ISSUE THREAD

**Issue by Galixte** [dmzx/hangman#2]
Hi,

there are some english strings in :

```
ext/dmzx/hangman/styles/all/template/hangman.js
```

Lines : 130, 158, 192, 226 and 234.

Could you ensure that these strings are translatables in common.php file?

Second request, could you ensure to customize the quotes in ACP ? (for usage in other language)

**Comment by Galixte** [comment]
Hi,

could you do something ?

**Comment by dmzx** [comment]
Updated the lang file only the fr files need to be checked.
Acp I will check

**Comment by Galixte** [comment]
Ok thanks for add the keys !

I will wait the possibility to customize the quotes in my language.
